### ISSUE TITLE
Small client freeze when "skip intro" button is used

### ISSUE THREAD

**Issue by tilda** [jellyfin/jellyfin-media-player#405]
**Describe the bug**
When using the "Skip Intro" functionality as part of said plugin, my client freezes for around 10-20 seconds. I've had this happen consistently over multiple series. This didn't happen before 1.9.0.

**To Reproduce**
1. Have "Skip Intro" enabled (of course on the server as well)
2. Start watching an episode until the button shows up
3. Click the button, and watch the client freeze up for a bit

**Expected behavior**
For the client to skip to the end of the intro without any freezes.

**Screenshots**
N/A.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 1.9.0
 - Installation Method: Official build, Windows installer.

**Additional context**
Closing the client while frozen gets audio playing for a couple seconds (but then closes the client, like it should).

**Comment by kstorbakken** [comment]
I'm having this issue with 1.9.0 as well with the skip intro button, it's not happening on 1.8.9. I do have additional lockups as well when pausing and trying to exit videos and such, it's very random. Sometimes it will happen, then it'll work the next time, then back to freezing. The freezing lasts about 30s then does the action selected.

**Comment by h1ght** [comment]
same on windows 10 22h2, prior to 1.9 it was working fine. now at my client just freezes, when closing the app sounds plays for some secs before its closed. tried to delete cache in appdata, issue still exist.

**Comment by iwalton3** [comment]
Does this happen just when skip intro is enabled or always?

**Comment by iwalton3** [comment]
If this is somehow caused by the MPV version change, this build will fix it: https://github.com/jellyfin/jellyfin-media-player/actions/runs/4457781601

**Comment by tilda** [comment]
> Does this happen just when skip intro is enabled or always?

This only happens when the plugin's function is used, so yes only when enabled. (I don't have patched frontend installed on the server so cannot test with that.)

Will try the other build later and see what that does.

**Comment by iwalton3** [comment]
I think the plugin does some strange stuff with MutationObserver so it could just be that.

**Comment by h1ght** [comment]
i tr

> If this is somehow caused by the MPV version change, this build will fix it: https://github.com/jellyfin/jellyfin-media-player/actions/runs/4457781601

i tried this build, works fine for windows, but its much slower compared to previous version.

**Comment by iwalton3** [comment]
Yeah I don't think that build is a fix. This is something I will have to dig into but I did notice UI component lagging myself at some point. It'll probably be a git bisect thing to be honest

**Comment by h1ght** [comment]
what u mean by lagging? like dragging the window on the screen? that was jerky before for me. not that fluent like other windows

**Comment by Wastfulajr** [comment]
I've had the same issue with certain media, clicking "Skip Intro" freezes up the client for 1-2 minutes before continuing. While it buffers, the app itself hangs temporarily while attempting to close.

**Comment by TheStachelfisch** [comment]
I also observed, that with some media the freeze is either longer or shorter. Sometimes it's only a few seconds while sometimes it's multiple minutes and often it never unfreezes.

**Comment by h1ght** [comment]
@Wastfulajr @TheStachelfisch are u using the linked build? https://github.com/jellyfin/jellyfin-media-player/issues/405#issuecomment-1475030711

**Comment by TheStachelfisch** [comment]
> @Wastfulajr @TheStachelfisch are u using the linked build? [#405 (comment)](https://github.com/jellyfin/jellyfin-media-player/issues/405#issuecomment-1475030711)

Yes

**Comment by Kunal926** [comment]
any fix yet?

**Comment by Kou-kun42** [comment]
Just wanted to add, this issue is still occurring on 1.9.1.  For me on mac playing mkv files it's not just a small freeze, I have to quit out and restart the app to continue playback.

**Comment by Wastfulajr** [comment]
I'm also still having this issue on build 1.9.1. Same as before it occasionally skips forward to the correct frame and then freezes requiring a restart, and occasionally unfreezes and continues after 1-2 minutes.

**Comment by SerbNerd** [comment]
I am on build 1.9.1 and more often than not my whole client is frozen once I click the skip intro button, requiring me to close the whole player. Interestingly enough, it starts playing after the intro when I relaunch the media. 

Side note: I have noticed my GPU go up in usage a bit when the lag occurs. Not sure if it's helpful but it almost looks like its trying to transcode something even though the video is direct playing.

**Comment by jacob1264** [comment]
Intro skipper was freezing my media player client, setting the cache from default to large or very large seemed to mostly fixed it. It stutters for a couple seconds but does not freeze

**Comment by ohitstom** [comment]
> I am on build 1.9.1 and more often than not my whole client is frozen once I click the skip intro button, requiring me to close the whole player. Interestingly enough, it starts playing after the intro when I relaunch the media.
> 
> Side note: I have noticed my GPU go up in usage a bit when the lag occurs. Not sure if it's helpful but it almost looks like its trying to transcode something even though the video is direct playing.

Exactly the same issue here, nvidia gpu using local playback.

**Comment by DestinyofYeet** [comment]
I fixed it by re-replacing the web folder with the dist folder as described [here](https://github.com/ConfusedPolarBear/intro-skipper/blob/master/docs/native.md)

**Comment by jacob1264** [comment]
Okay guys I think I finally figured it out, if you have replaced the web client on the server you must disable the Skip Intro plugin from the Jellyfin Web Client Settings. If you did not install the alternate web client server side you must enable the Skip Intro plugin. You can not do both! I haven't dug into the code past this, but injectSkipIntroHtml() seems to throw an error and time out, which may cause errors in the playback manager.

Here is the line that calls the offending code:

Line 121 - C:\Program Files\Jellyfin\Jellyfin Media Player\web-client\extension\skipIntroPlugin.js
`await injectSkipIntroHtml(); // I have trust issues`

Since disabling the plugin the Skip Intro button works flawlessly, just like on the web client.

**Comment by jacob1264** [comment]
I have tried many fixes, none of them seem to work flawlessly. I disabled the intro skipper plugin in the desktop client and it solved 90% of the issues. The desktop player just used the server's version. Enabling both the server version and the desktop plugin causes it to freeze a lot more.

Line 121 - C:\Program Files\Jellyfin\Jellyfin Media Player\web-client\extension\skipIntroPlugin.js
`await injectSkipIntroHtml(); // I have trust issues`

I tried to figure it out but I don't know how to properly debug Jellyfin.

**Comment by TheFeelTrain** [comment]
My server doesn't have the intro skipper web client but I still get the freeze, so I don't think that is related. Although it could be another bug causing a similar thing. I am also 95% sure it used to work fine in 1.8.x so it was almost certainly something that changed in 1.9.x that is the cause because it did work properly at one point. Which also means it's probably unrelated to anything server-side in general.

**Comment by jacob1264** [comment]
I thought changing the cache size fixed it for me but it just masked it. You may find Intro Skip will freeze again after a few episodes, especially episodes with larger filesizes.

After your report I am 80% confident that the bug lies within the Skip Intro plugin itself within the desktop client. And maybe 20% in our environments, I am not running proper tests but in my latest experiment I have found:

With the plugin disabled: 
Only using the injected web plugin, I have had zero freezes and no lag after playing several hours of content and manually clicking skip intros. The skip intro function is instant.

With the desktop skip intro plugin enabled:
Skip intros lag for a second at first, as episodes are play the lag seems to get worse.
After a few episodes have played, clicking the Skip Intro button almost guarantees to cause the program to hang or freeze for a long time.

I don't really see a need to use the desktop plugin, I can't find a downside using the server side version.

**Comment by ashu54-aseem** [comment]
I have been experiencing this bug for some time now. Here are my observations:

It gets worse on subsequent playbacks in a session, regardless of whether or not the button is used.
There are no issues with other clients or jellyfin-web, so I think this is a client-specific issue.
On terminating the app after it has frozen, playback resumes after the intro, so the intro is skipped successfully.
On waiting out after the playback/player has frozen, it sometimes resumes the playback after 5/10 minutes.

**Comment by dmandrone** [comment]
To clarify, is this still being addressed?

Saw that the commit to solve this issue was deleted, so wanted to be sure.

**Comment by TheStachelfisch** [comment]
> To clarify, is this still being addressed?
> 
> Saw that the commit to solve this issue was deleted, so wanted to be sure.

It still shows up for me. Doesn't seem to be deleted in any way

**Comment by dmandrone** [comment]
> > To clarify, is this still being addressed?
> > Saw that the commit to solve this issue was deleted, so wanted to be sure.
> 
> It still shows up for me. Doesn't seem to be deleted in any way

I completely misread the notes. The testing branch was deleted. Apologies.

But on this topic, this issue still seems to persist, at least on my end.

To avoid myself saying anything else dumb in confusion, the fix is completed but pending release, correct?

**Comment by iwalton3** [comment]
Correct nothing has been released yet. Probably will wait for another maintenance release unless something major comes up.

**Comment by TheStachelfisch** [comment]
> > > To clarify, is this still being addressed?
> > > Saw that the commit to solve this issue was deleted, so wanted to be sure.
> > 
> > It still shows up for me. Doesn't seem to be deleted in any way
> 
> I completely misread the notes. The testing branch was deleted. Apologies.
> 
> But on this topic, this issue still seems to persist, at least on my end.
> 
> To avoid myself saying anything else dumb in confusion, the fix is completed but pending release, correct?

If you want to use it right now you would need to either build the app yourself or fork the repo and run a Github action to build it, since I don't think an action ran, when the PR was merged

**Comment by iwalton3** [comment]
Well that I can just do. https://github.com/jellyfin/jellyfin-media-player/actions/runs/5373776249

**Comment by funkey7dan** [comment]
This same issue still happens to me on 1.9.1 - not every use, but usually after skipping intro once, happens on the next episode

**Comment by Alexk2309** [comment]
The issue still happens im usually still getting freezes using 1.9.1, well the skipping experience is not as smooth as using the web version of jellyfin.

**Comment by menixator** [comment]
For any nix users looking at this issue, here's an overlay. Sadly, it'll actually build it on your system even though the skipIntroPlugin.js lives independently.

```nix
{ pkgs, ... }: {

  # Fixes an issue with jmp where clicking the skip intro makes the player freeze
  # https://github.com/jellyfin/jellyfin-media-player/issues/405#issuecomment-1606572053
  nixpkgs.overlays = [
    (final: prev: {
      jellyfin-media-player = prev.jellyfin-media-player.overrideAttrs (finalAttrs: prevAttrs: {
        patches = (prevAttrs.patches or [ ]) ++ [

          (final.pkgs.writeText
            "jellyfin-media-player-skip-intro.patch"
            /*diff*/
            ''
              --- a/native/skipIntroPlugin.js	1970-01-01 05:00:01.000000000 +0500
              +++ b/native/skipIntroPlugin.js	2024-01-16 10:34:09.215694918 +0500
              @@ -84,6 +84,13 @@
                               });
                           }
 
              +            function handleClick(e) {
              +                e.preventDefault();
              +                e.stopPropagation();
              +                skipIntro();
              +                document.querySelector('.skipIntro .btnSkipIntro').removeEventListener('click', handleClick, { useCapture: true });
              +            }
              +
                           async function injectSkipIntroHtml() {
                               const playerContainer = await waitForElement('.upNextContainer', 5000);
                               // inject only if it doesn't exist
              @@ -91,11 +98,7 @@
                                   playerContainer.insertAdjacentHTML('afterend', skipIntroHtml);
                               }
 
              -                document.querySelector('.skipIntro .btnSkipIntro').addEventListener('click', (e) => {
              -                    e.preventDefault();
              -                    e.stopPropagation();
              -                    skipIntro();
              -                }, { useCapture: true });
              +                document.querySelector('.skipIntro .btnSkipIntro').addEventListener('click', handleClick, { useCapture: true });
 
                               if (window.PointerEvent) {
                                   document.querySelector('.skipIntro .btnSkipIntro').addEventListener('pointerdown', (e) => {
            ''
          )
        ];
      });
    })

  ];


}

```

**Comment by viggy96** [comment]
> Correct nothing has been released yet. Probably will wait for another maintenance release unless something major comes up.

When is the next maintenance release of JMP scheduled?

**Comment by ashu54-aseem** [comment]
Hey @iwalton3, can you rerun the build action in the meanwhile? Seems like the artifacts have expired.
